# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://hackwill.github.io/landing-page/
title: Safedeliv
email: willmechler@gmail.com
author: William Mechler
description: > 
 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/?lang=en 
  - title: github
    url: https://github.com/hackwill
  - title: Email
    url: mailto:willmechler@gmail.com
