# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Your Awesome Site
email: willmechler@gmail.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2018 William Mechler. All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/?lang=en
  - title: github
    url: https://github.com/hackwill
  - title: linkedin
    url: 
